### WHILE ####
x=1
while x <= 10:  #While con un boolean condition
    print("This line has been pointed",) #Adicionando una coma, hacemos que no se imprima el salto de linea
    print( x,)
    print ("lines")
    x = x + 1


### FOR ####
for x in range(0,10):
    print ("Line generated by for",)
    print (x,)
    print (" - ")


### FACTORIAL FUNCTION ####

def factorial(number):
    result = 1
    while number > 0:
        result = result*number
        number = number-1
    return result

inVariable = input("Ingresa el numero para calcular el factorial con While: ")
print(factorial(int(inVariable)))

def factorialFor(number):
    result = 1
    for x in range(1,number+1):
        result = result*x
    return result

inVariable = input("Ingresa el numero para calcular el factorial con For: ")

print(factorialFor(int(inVariable)))
    
    
